name: Build & Release

on:
  push:
    branches:
      - master

permissions:
  contents: write
  
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  

      - name: Restore
        run: dotnet restore

      - name: Compile
        run: dotnet publish -c Release -o out

      - name: Zip it
        run: |
            cd out
            zip -r ../build.zip ./*
            cd ..

      - name: Release
        uses: ncipollo/release-action@v1
        with:
                tag: latest
                name: Latest Build
                body: Latest build
                allowUpdates: true
                replacesArtifacts: true
                artifacts: build.zip
        env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}