name: Build & Upload Release (cross-platform)

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]  # puoi tenere solo uno se vuoi

    steps:
      - name: Checkout del codice
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Ripristina pacchetti
        run: dotnet restore

      - name: Compila l'app
        run: dotnet publish -c Release -o out

      - name: Estrai short SHA
        shell: bash
        run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Crea ZIP (Linux)
        if: runner.os == 'Linux'
        run: zip -r "build-${{ env.SHORT_SHA }}.zip" ./out

      - name: Crea ZIP (Windows)
        if: runner.os == 'Windows'
        run: Compress-Archive -Path out\* -DestinationPath "build-${{ env.SHORT_SHA }}.zip"

      - name: Crea/Aggiorna release su GitHub
        uses: ncipollo/release-action@v1
        with:
          tag: latest
          name: Latest Build - ${{ env.SHORT_SHA }}
          body: |
            Build automatica dal commit `${{ github.sha }}`.
          allowUpdates: true
          replacesArtifacts: true
          artifacts: build-${{ env.SHORT_SHA }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}