name: Build & Upload Release (cross-platform)

on:
  push:
    branches:
      - dev

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]  # puoi tenere solo uno se vuoi

    steps:
      - name: Checkout del codice
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Ripristina pacchetti
        run: dotnet restore

      - name: Compila l'app
        run: dotnet publish -c Release -o out


      - name: Crea ZIP (Linux)
        if: runner.os == 'Linux'
        run: zip -r "build-linux.zip" ./out

      - name: Crea ZIP (Windows)
        if: runner.os == 'Windows'
        run: Compress-Archive -Path out\* -DestinationPath "build-win.zip"

      - name: Crea/Aggiorna release su GitHub
        uses: ncipollo/release-action@v1
        with:
          prerelease: true
          name: Latest dev build
          body: Latest dev build
          allowUpdates: true
          replacesArtifacts: true
          artifacts: build-linux.zip,build-win.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}